init:
  - git config --global core.autocrlf input
install: 
  - ps: Install-Product node 0.11
  - cmd: dir c:\nodist\bin
build_script:
  - cmd: build.cmd
test: off
version: 0.0.1.{build}
artifacts:
  - path: bin
    name: bin
